name: Node.js Package
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - run: npm ci
      - run: npx nx affected --parallel=2 --target=lint --base=HEAD~1 --head=HEAD
      - run: npx nx affected --parallel=2 --target=publish --tag=latest --base=HEAD~1 --head=HEAD
